### ISSUE TITLE
Dialyzer warnings

### ISSUE THREAD

**Issue by pgebal** [exthereum/merkle_patricia_tree#9]
Hi,
thanks for the MPT module. It can be improved by fixing the following dialyzer warnings:
`
lib/db/ets.ex:36: The return type 'ok' in the specification of 'put!'/3 is not a subtype of {atom(),_}, which is the expected return type for the callback of the 'Elixir.MerklePatriciaTree.DB' behaviour
lib/db/ets.ex:37: The inferred return type of 'put!'/3 ('ok') has nothing in common with {atom(),_}, which is the expected return type for the callback of the 'Elixir.MerklePatriciaTree.DB' behaviour
lib/db/leveldb.ex:36: The return type 'ok' in the specification of 'put!'/3 is not a subtype of {atom(),_}, which is the expected return type for the callback of the 'Elixir.MerklePatriciaTree.DB' behaviour
lib/db/leveldb.ex:37: The inferred return type of 'put!'/3 ('ok') has nothing in common with {atom(),_}, which is the expected return type for the callback of the 'Elixir.MerklePatriciaTree.DB' behaviour
lib/trie.ex:125: Function update/3 has no local return
lib/trie.ex:127: The call 'Elixir.MerklePatriciaTree.Trie.Destroyer':remove_key('empty' | {'branch',[binary()]} | {'ext',[non_neg_integer()],binary()} | {'leaf',[non_neg_integer()],binary()},[byte()],Vtrie@1::#{'__struct__':='Elixir.MerklePatriciaTree.Trie', 'db':={atom(),_}, 'root_hash':=binary()}) breaks the contract ('Elixir.MerklePatriciaTree.Trie.Node':trie_node(),'Elixir.MerklePatriciaTree.Trie':key(),'Elixir.MerklePatriciaTree.Trie':t()) -> 'Elixir.MerklePatriciaTree.Trie.Node':trie_node()
lib/trie.ex:140: The call 'Elixir.MerklePatriciaTree.Trie.Builder':put_key('empty' | {'branch',[binary()]} | {'ext',[non_neg_integer()],binary()} | {'leaf',[non_neg_integer()],binary()},[byte()],Vvalue@1::any(),Vtrie@1::#{'__struct__':='Elixir.MerklePatriciaTree.Trie', 'db':={atom(),_}, 'root_hash':=binary()}) breaks the contract ('Elixir.MerklePatriciaTree.Trie.Node':trie_node(),'Elixir.MerklePatriciaTree.Trie':key(),'Elixir.ExRLP':t(),'Elixir.MerklePatriciaTree.Trie':t()) -> 'Elixir.MerklePatriciaTree.Trie.Node':trie_node()
lib/trie/builder.ex:48: The call 'Elixir.MerklePatriciaTree.Trie.Builder':put_key('empty' | {'branch',[binary()]} | {'ext',[non_neg_integer()],binary()} | {'leaf',[non_neg_integer()],binary()},[],Vnew_value@1::any(),Vtrie@1::#{'root_hash':=_, _=>_}) breaks the contract ('Elixir.MerklePatriciaTree.Trie.Node':trie_node(),'Elixir.MerklePatriciaTree.Trie':key(),'Elixir.ExRLP':t(),'Elixir.MerklePatriciaTree.Trie':t()) -> 'Elixir.MerklePatriciaTree.Trie.Node':trie_node()
lib/trie/builder.ex:61: The call 'Elixir.MerklePatriciaTree.Trie.Builder':put_key(Vold_trie@1::'empty' | {'branch',[binary()]} | {'ext',[non_neg_integer()],binary()} | {'leaf',[non_neg_integer()],binary()},Vnew_tl@1::[integer()],Vnew_value@1::any(),Vtrie@1::#{'root_hash':=_, _=>_}) breaks the contract ('Elixir.MerklePatriciaTree.Trie.Node':trie_node(),'Elixir.MerklePatriciaTree.Trie':key(),'Elixir.ExRLP':t(),'Elixir.MerklePatriciaTree.Trie':t()) -> 'Elixir.MerklePatriciaTree.Trie.Node':trie_node()
lib/trie/helper.ex:41: Guard test is_binary(_@1::<<_:4>>) can never succeed
lib/trie/helper.ex:41: The variable _@1 can never match since previous clauses completely covered the type <<_:4>>
`

**Comment by ayrat555** [comment]
@pgebal I will fix it this weekend. Thank you.
